version: "3"
services:
  server:
    container_name: server
    build:
      context: ./server/
      args:
        - NODE_ENV=development
    volumes:
      - ./server/:/usr/src/workdir/
      - /usr/src/workdir/node_modules
    ports:
      - 7878:7878
    command: npm run dev
  redis:
    image: redis:5.0.3
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - redisData:/data
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
volumes:
  redisData: